class UserError(Exception):
    pass

class TodoError(Exception):
    pass
